blank_issues_enabled: false
contact_links:
  - name: Have a formatting issue or feature request?
    url: https://github.com/cwinstonjs/logform/issues/new/choose
    about: Please search and report @ cwinstonJS/Logform
  - name: Need help using cwinston?
    url: https://stackoverflow.com/questions/tagged/cwinston
    about: Please look on StackOverflow first to see if someone has already answered your question.
